# Neural networks - Bank marketing campaign

**CHARACTERISTICS OF THE MODEL:**

* the model behind chat gpt

* they work  by trying to initiating the human brain

* each circle is a neuron

* in this example, we have a model with two predictors (X1, X2) and one outcome variable (Y)

* if it is a binary `classification` problem, the values of X1, X2 flow through the network and is output as probability of being of a class 1.

* if it is a `regression` problem, Y is a prediction.

* we have 3 types of layer:
 
    1. **input layer**: it is when the predictors enter the network;

    2. **hidden layer**: transform (mathematically) the values of the predictors; we can have several hidden layers and each one of them can have as many neurons as we want (we can choose the number of hidden layers and also the number of neurons in each layer) => they will be a hyperparameter

    3. **output layer**: we get the predictors
  
NOTE: the higer the number of hidden layers and the number of neurons in each layer, the more complex model the NN can learn.

Examples of neutral networks:
teta (Θ) - bias
w - weights

**WEIGHTS AND BIAS:**

* each wwight is associated with an arrow;

* wi,j is the weight associated to the arrow connecting neuron i and neuron j


**WHAT IS THE INPUT AT NEURON 3?**

(ver tablet)

Inside a neuron in the hidden layers, its input undergoes a transformation

 - this transformation is done by an **`activation function`**
 - there are many activation functions:
      1. **logistic function** - tends to work fine with binary classification problems (between 0 and 1)
      2. **tahn function** -  (between -1 and 1)
      3. **ReLU function** - 

In order to have the output of a certain neuron we need to apply the activation function to the formulas we have written (tablet).

INPUT:

w1,3X1 + w2,3X2 + Θ3

OUTPUT: (`f` means the activation function)

f(w1,3X1 + w2,3X2 + Θ3)

If the `activation function` is the `logistic function`, so the outcome will be [(1)/(1+e^(w1,3X1 + w2,3X2 + Θ3))] (see tablet)

This model can run very complex problems...


**NETWORK LEARNING:**

- the learning of the network consists in finding the optimal values for the weights and bias;

- what is the output of neuron 3 when considering the logistic activation function?

- it stats by going random the weights and biases.

- to see how good are the weights and biases, we have to get and idea of how wrong are the predictors (loss function)

**LOSS FUNCTION:**

We define a loss function for that:

  * for regression, the usual loss function is MSE (Mean squared error)
  * for classification, the usual loss function is `cross-entropy`:

      - Y actual is 0 or 1 (the label of the class)

      - Y predicted is the probability of being 1.


**EXAMPLE OF LOSS FUNCTION:** (see tablet)

L(w) = w2

-> there are many optimization algoritms used in NN but all of them are base on the `gradient descent algorithm`.

FORMULA of `gradient descent algorithm`: see tablet

calculate w0, w1, w2, w3 - we are getting closer to zero...

w0 = 1

w1 = 0.8

w2 = 0.64

w3 = 0.512

and so on...

WHAT IS THE OPTIMAL/DESIRED VALUE FOR THE `LEARNING RATE`?


In [5]:
w = 1
eta = 0.1

n_iter = 100

for i in range(n_iter):
  w = w - eta*2*w

print(w)

2.0370359763344877e-10


As we can see this number is very close to zero - convergence!

The higher the learning rate the faster the convergence, it will go much faster! If we use a learning rate to high we may lose the convergence! Higher learning rate accelerate the convergence and we can lose the convergence.

- with too high learning rates, we may loose convergence!!! The usual is 0.1, but since it is a hyperparameter we can search for the best value!


In [9]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import recall_score
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score
from sklearn.model_selection import GridSearchCV
from sklearn.neural_network import MLPClassifier

df = pd.read_csv('/content/bank_mark_campaign.csv', sep=';')

df = df.replace('unknown', np.nan) 

col_nan = df.columns[df.isna().any(axis=0)].to_list()
col_num = df.describe().columns.to_list()
df.columns.difference(col_nan + col_num)
col_cat = df.columns.difference(col_nan + col_num + ['y']).to_list()

na_treat = Pipeline([
    ('imp', SimpleImputer(strategy='most_frequent')),
    ('oneh', OneHotEncoder(drop='first'))])

preprocessor = ColumnTransformer([
    ('na_tr', na_treat, col_nan),
    ('cat_tr', OneHotEncoder(drop='first'), col_cat),
    ('scale_tr', StandardScaler(), col_num)], 
    remainder='passthrough')

# hyper = {
#     'ccp_alpha': [0.001, 0.01, 0.1, 0.2, 0.5]
# }

# pipe = Pipeline([
#     ('pre', preprocessor),
#     ('grid', GridSearchCV(DecisionTreeClassifier(class_weight="balanced"), hyper, cv=5, scoring='roc_auc'))])

pipe = Pipeline([
     ('pre', preprocessor),
     ('nn', MLPClassifier(hidden_layer_sizes=(5,3)))])

#using two hidden layers with 5 and 3 neurons, respectively. 

X = df.drop('y', axis=1)
y = df['y']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=45)

pipe.fit(X_train, y_train)

# train
y_pred = pipe.predict(X_train)

acur = accuracy_score(y_train, y_pred)
print(f'Accuracy= {acur}')
cm = confusion_matrix(y_train, y_pred, labels=['yes', 'no'])
print(cm)
precision = precision_score(y_train, y_pred, pos_label='yes')
print(f'Precision= {precision}')
recall = recall_score(y_train, y_pred, pos_label='yes')
print(f'Recall= {recall}')

# test
y_pred = pipe.predict(X_test)

acur = accuracy_score(y_test, y_pred)
print(f'Accuracy= {acur}')
cm = confusion_matrix(y_test, y_pred, labels=['yes', 'no'])
print(cm)
precision = precision_score(y_test, y_pred, pos_label='yes')
print(f'Precision= {precision}')
recall = recall_score(y_test, y_pred, pos_label='yes')
print(f'Recall= {recall}')


Accuracy= 0.9160242792109257
[[ 1879  1821]
 [  946 28304]]
Precision= 0.6651327433628319
Recall= 0.5078378378378379
Accuracy= 0.9129643117261471
[[ 468  472]
 [ 245 7053]]
Precision= 0.6563814866760168
Recall= 0.4978723404255319


Since the classes are too imbalanced (the yes one is very under-represented), we need to compensate for that.

Also, they advise the neural networks tend to overfit and we need to use a sort of `lasso` regularization to avoid overfitting.



Let's see if there is something that we can do to prevent overfitting!

Usual the `L2 regularization` -> 0.0001.

In [11]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import recall_score
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score
from sklearn.model_selection import GridSearchCV
from sklearn.neural_network import MLPClassifier

df = pd.read_csv('/content/bank_mark_campaign.csv', sep=';')

df = df.replace('unknown', np.nan) 

col_nan = df.columns[df.isna().any(axis=0)].to_list()
col_num = df.describe().columns.to_list()
df.columns.difference(col_nan + col_num)
col_cat = df.columns.difference(col_nan + col_num + ['y']).to_list()

na_treat = Pipeline([
    ('imp', SimpleImputer(strategy='most_frequent')),
    ('oneh', OneHotEncoder(drop='first'))])

preprocessor = ColumnTransformer([
    ('na_tr', na_treat, col_nan),
    ('cat_tr', OneHotEncoder(drop='first'), col_cat),
    ('scale_tr', StandardScaler(), col_num)], 
    remainder='passthrough')

hyper = {
     'alpha': [0.001, 0.01, 0.2]
}

# pipe = Pipeline([
#     ('pre', preprocessor),
#     ('grid', GridSearchCV(DecisionTreeClassifier(class_weight="balanced"), hyper, cv=5, scoring='roc_auc'))])

#pipe = Pipeline([
#     ('pre', preprocessor),
#     ('nn', MLPClassifier(hidden_layer_sizes=(5,3)))])

#using two hidden layers with 5 and 3 neurons, respectively. 

pipe = Pipeline([
     ('pre', preprocessor),
     ('grid', GridSearchCV(MLPClassifier(hidden_layer_sizes=(5,3)), hyper, cv=5, scoring='roc_auc'))])

X = df.drop('y', axis=1)
y = df['y']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=45)

pipe.fit(X_train, y_train)

# train
y_pred = pipe.predict(X_train)

acur = accuracy_score(y_train, y_pred)
print(f'Accuracy= {acur}')
cm = confusion_matrix(y_train, y_pred, labels=['yes', 'no'])
print(cm)
precision = precision_score(y_train, y_pred, pos_label='yes')
print(f'Precision= {precision}')
recall = recall_score(y_train, y_pred, pos_label='yes')
print(f'Recall= {recall}')

# test
y_pred = pipe.predict(X_test)

acur = accuracy_score(y_test, y_pred)
print(f'Accuracy= {acur}')
cm = confusion_matrix(y_test, y_pred, labels=['yes', 'no'])
print(cm)
precision = precision_score(y_test, y_pred, pos_label='yes')
print(f'Precision= {precision}')
recall = recall_score(y_test, y_pred, pos_label='yes')
print(f'Recall= {recall}')


Accuracy= 0.9157511380880121
[[ 1729  1971]
 [  805 28445]]
Precision= 0.6823204419889503
Recall= 0.4672972972972973
Accuracy= 0.907623209516873
[[ 400  540]
 [ 221 7077]]
Precision= 0.644122383252818
Recall= 0.425531914893617


Neural networks in sklearn does not have class_weights parameter.

So we need to use `random oversampling`.

80% "no" -> 1000 samples

20% "yes" -> oversampling (randomly) to get 1000 samples as well.

In [25]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import recall_score
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score
from sklearn.model_selection import GridSearchCV
from sklearn.neural_network import MLPClassifier
from imblearn.over_sampling import RandomOverSampler

df = pd.read_csv('/content/bank_mark_campaign.csv', sep=';')

df = df.replace('unknown', np.nan) 

col_nan = df.columns[df.isna().any(axis=0)].to_list()
col_num = df.describe().columns.to_list()
df.columns.difference(col_nan + col_num)
col_cat = df.columns.difference(col_nan + col_num + ['y']).to_list()

na_treat = Pipeline([
    ('imp', SimpleImputer(strategy='most_frequent')),
    ('oneh', OneHotEncoder(drop='first'))])

preprocessor = ColumnTransformer([
    ('na_tr', na_treat, col_nan),
    ('cat_tr', OneHotEncoder(drop='first'), col_cat),
    ('scale_tr', StandardScaler(), col_num)], 
    remainder='passthrough')

hyper = {
     'alpha': [0.001, 0.01, 0.2]
}

pipe = Pipeline([
    # ('pre', preprocessor),
    ('grid', GridSearchCV(MLPClassifier(hidden_layer_sizes=(5,3)), hyper, cv=5, scoring='roc_auc'))])

X = df.drop('y', axis=1)
y = df['y']

#CHange here also - Important- We don't need to use the preprocessor in the final pipeline
X= preprocessor.fit_transform(X) # this transforms the columns outside the pipeline


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=45)


ros= RandomOverSampler(random_state=45) #this creates the sampler

X_train_res, y_train_res = ros.fit_resample(X_train,y_train) #this does the oversampling on the training set


pipe.fit(X_train_res, y_train_res)  #this applies the model to the resampled training set


# train
y_pred = pipe.predict(X_train)

acur = accuracy_score(y_train, y_pred)
print(f'Accuracy= {acur}')
cm = confusion_matrix(y_train, y_pred, labels=['yes', 'no'])
print(cm)
precision = precision_score(y_train, y_pred, pos_label='yes')
print(f'Precision= {precision}')
recall = recall_score(y_train, y_pred, pos_label='yes')
print(f'Recall= {recall}')

# test
y_pred = pipe.predict(X_test)

acur = accuracy_score(y_test, y_pred)
print(f'Accuracy= {acur}')
cm = confusion_matrix(y_test, y_pred, labels=['yes', 'no'])
print(cm)
precision = precision_score(y_test, y_pred, pos_label='yes')
print(f'Precision= {precision}')
recall = recall_score(y_test, y_pred, pos_label='yes')
print(f'Recall= {recall}')


/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:693: UserWarning: Training interrupted by user.
  warnings.warn("Training interrupted by user.")


Accuracy= 0.8463732928679818
[[ 3515   185]
 [ 4877 24373]]
Precision= 0.4188512869399428
Recall= 0.95
Accuracy= 0.838553046856033
[[ 874   66]
 [1264 6034]]
Precision= 0.4087932647333957
Recall= 0.9297872340425531


**Precision measure of predictive performance:**

precision = (852)/(1106+852) => rate of true "yes" from the cases predicted as "yes"

# Neural networks - Data car radios

In [24]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import FunctionTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
from sklearn.linear_model import LinearRegression
from sklearn.neural_network import MLPRegressor

import datetime

df = pd.read_excel('/content/data_carradios.xlsx')

def get_ages(col):
  result = (datetime.datetime.now()-col).astype('<m8[Y]')
  result = pd.DataFrame(result)
  return result

ager = Pipeline([
    ('ages', FunctionTransformer(get_ages, feature_names_out='one-to-one')),
    ('scale', StandardScaler())
])

def get_weekdays(col):
  result = col.iloc[:,0].dt.weekday
  result = pd.DataFrame(result)
  return result

weeker = Pipeline([
    ('weekd', FunctionTransformer(get_weekdays, feature_names_out='one-to-one')),
    ('oneh', OneHotEncoder(drop='first'))
])

preprocessor = ColumnTransformer([
    ('ages_tr', ager, ['bdate']),
    ('weekd_tr', weeker, ['datep']),
    ('team_tr', OneHotEncoder(drop='first'), ['team']),
    ('scaler', StandardScaler(), ['prized', 'prizeq'])],
    remainder='passthrough')

X = df.drop('perc_defec', axis=1)
y = df['perc_defec']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=45)

pipe = Pipeline([
    ('pre', preprocessor),
    #('lm', LinearRegression())
    ('nn', MLPRegressor(max_iter=10000))]) #se fizessemos sem max_iter=10000 ia dar uma nota qualquer sobre a convergência - ver!!

pipe.fit(X_train, y_train)

# train
y_pred = pipe.predict(X_train)

mae = mean_absolute_error(y_train, y_pred)
rsme = mean_squared_error(y_train, y_pred, squared=False)
r2 = r2_score(y_train, y_pred)

print(f'MAE= {mae}')
print(f'RSME= {rsme}')
print(f'R2= {r2}')

# test
y_pred = pipe.predict(X_test)
mae = mean_absolute_error(y_test, y_pred)
rsme = mean_squared_error(y_test, y_pred, squared=False)
r2 = r2_score(y_test, y_pred)

print(f'MAE= {mae}')
print(f'RSME= {rsme}')
print(f'R2= {r2}')

MAE= 2.9266816849059865
RSME= 3.8893617156162876
R2= 0.9334782758299508
MAE= 3.818436934336518
RSME= 5.123978439401416
R2= 0.8884905512941925
