**NUMPY** **ARRAYS**

Package that deals with arrays (tipically with numbers)
Used to do calculations
ARRAY => matrix lik: 
v=[1 2 3] 1D
a=[1 2 3]
  [2 3 7]
-We need to import numpy library (import numpy)


Exercise 10-a) manual numeration

In [ ]:
import numpy as np #do this only once

instead of import numpy several times, i.e., when we need, we just need to call np.

In [ ]:
a = np.array([1, 2, 3, 4])

In [ ]:
a

array([1, 2, 3, 4])

Exercise 10b) using the function range
because this numbers are consecutive we can use the range function of the previous lecture


In [ ]:
a = np.array(range(1,4+1))
a

array([1, 2, 3, 4])

NOTE: in the range function with interval the firts number is always included, i.e., will show up, but the second number, i.e., the last of the interval is not included => so we need to put the number we want plus 1. in this case we want 4, so 5 (4+1)

Exercise 10c) using the np.arange function

In [ ]:
a = np.arange(1, 4+1)
a

array([1, 2, 3, 4])

Until now we have been doing 1D array, now we will do 2D array

Numpy can create ranges with all statistical distribution, but we only want this:
=> discrete uniform distribution: all numbers have the same probability of showing up - this means that with an array with 1, 2, 3, the numbers have the same probability of showing up

**Exercise 11**- create a 2D numpy array:
array([[1, 2, 3, 4],
      [8, 9, 6, 5]])

a) using manual numeration

In [ ]:
a = np.array([[1, 2, 3, 4],
             [8, 9, 6, 5]])

b) Using manual function np.reshape

In [ ]:
a = a.reshape(2,4)

**Exercise 12** - create a 2D numpy array (3 x 4), whose elements are randomly
drawn from the discrete uniform distribution between 2 (inclusive) and 30
(inclusive)

NOTE: the reshape function allow us to present the array as a matrix

In [ ]:
np.random.seed(7548)
a = np.random.randint(2, 30+1, size=3*4)
a = a.reshape(3,4)

a) Obtain a numpy array, which contains the sums of each row of the numpy
array
=> sum of the lines - use axis = 1

In [ ]:
a.sum(axis=1)

array([52, 49, 62])

b) Obtain a numpy array, which contains the sums of each column of the numpy
array => sum of the colums - use axis=0

In [ ]:
a.sum(axis=0)

163

In [ ]:
a.mean(axis=1)

array([13.  , 12.25, 15.5 ])

c) Obtain a numpy array, which, per row, counts the number of elements greater
than 15

In [ ]:
a > 15

array([False, False,  True, False,  True, False, False, False, False,
        True, False,  True])

In python, in sums, true becomes 1 and false o.

In [ ]:
np.sum(True)

1

In [ ]:
np.sum(False)

0

In [ ]:
np.sum(a > 15, axis=1)

array([1, 1, 2])

d) Obtain a numpy array, which, per column, counts the number of elements
lower than 20

In [ ]:
np.sum(a < 20, axis=0)

array([2, 2, 2, 3])

**Exercise 13**

To put the courses in the same array

In [ ]:
course1 = [15, 18, 19]
course2 = [18, 19, 14]
course3 = [14, 16, 17]

np.array([course1, course2, course3])

array([[15, 18, 19],
       [18, 19, 14],
       [14, 16, 17]])

NOTE: this array is not the same as have a table (a ordem dos dados) because the first row corresponds to the 1st column in the table (1st column is course1)
So we need to transpose the marks (.T)

In [ ]:
course1 = [15, 18, 19]
course2 = [18, 19, 14]
course3 = [14, 16, 17]

marks = np.array([course1, course2, course3])
marks = marks.T
marks

array([[15, 18, 14],
       [18, 19, 16],
       [19, 14, 17]])

We are multiplying each course by its credits (course1*credits1), being credits1=6

In [ ]:
credits = np.array([6, 4.5, 3])

marks * credits

array([[ 90. ,  81. ,  42. ],
       [108. ,  85.5,  48. ],
       [114. ,  63. ,  51. ]])

In [ ]:
np.sum(marks * credits, axis=1) / np.sum(credits)

array([15.77777778, 17.88888889, 16.88888889])

Para arredondar para 2 digitos decimais

In [ ]:
np.round(np.sum(marks * credits, axis=1) / np.sum(credits), 2)

array([15.78, 17.89, 16.89])

**Exercise 14**

3D arrays:
=> numpy arrays can have an arbitrary number of dimensions;
=> more than 2 dimensions are used in image processing (we are not going to work with image)
=> prediction models are used with images (for instance, to predict diseases from organ images)

Creates a 3D numpy array (4 x 2 x 5), whose elements are randomly drawn from the integer uniform distribution between 2 (inclusive) and 30 (inclusive)

In [ ]:
np.random.seed(124)

a = np.random.randint(2, 30+1, size = 4*2*5)
a = a.reshape(4, 2, 5)
a

array([[[16, 30, 19,  9,  4],
        [11,  2, 22, 22, 30]],

       [[16, 23, 23, 24, 30],
        [29, 11, 24, 16, 18]],

       [[10, 11, 11,  2,  4],
        [20, 19,  3, 11, 15]],

       [[13,  3, 27, 12,  6],
        [28,  3, 21, 23, 24]]])

its necessary to have 3dimensions for image processing for example

a) What instruction, that uses the created numpy array, would produce the following numpy array: array([[55, 67, 80, 47, 44],
[88, 35, 70, 72, 87]])

NOTE: 1st number of the 1st row 16+16+10+13=55
      1st number of the 2nd row 11+29+20+28=88


In [ ]:
a.sum(axis=0)

array([[55, 67, 80, 47, 44],
       [88, 35, 70, 72, 87]])

b) What instruction, that uses the created numpy array, would produce the following numpy array: array([[27, 32, 41, 31, 34],
[45, 34, 47, 40, 48],
[30, 30, 14, 13, 19],
[41, 6, 48, 35, 30]])


NOTE: 1st number of the 1st row 16+11=27
      1st number of the second row 16+29=45

In [ ]:
a.sum(axis=1)

array([[27, 32, 41, 31, 34],
       [45, 34, 47, 40, 48],
       [30, 30, 14, 13, 19],
       [41,  6, 48, 35, 30]])

c) What instruction, that uses the created numpy array, would produce the following
numpy array: array([[ 78, 87],
[116, 98],
[ 38, 68],
[ 61, 99]])


NOTE: 78=soma dos números da primeira linha
87=soma dos números da segunda linha

In [ ]:
a.sum(axis=2)

array([[ 78,  87],
       [116,  98],
       [ 38,  68],
       [ 61,  99]])

PANDA DATAFRAMES

=> they are the appropriate type of object to store datasets

**Exercise 16**

Exercise 16a) Write a program that creates a dataframe, df, using a dictionary

In [ ]:
import pandas as pd

df = pd.DataFrame({'Students': ['John', 'Catherine', 'Mary'],
              'Ages': [18, 30, 25]})
df

Students  Ages
0       John    18
1  Catherine    30
2       Mary    25

Exercise 16b) Write a program that creates a dataframe, df, using a 2D numpy array

**READING AND WRITING DATA FILES**

**Exercise 17** - Create a program that reads to a pandas dataframe the file: car_radios.xlsx

In [ ]:
df = pd.read_excel('data_carradios.xlsx')
df

FileNotFoundError: ignored

CSV => files where the values are separatedby commas

**Exercise 18** - Create a program that reads to a pandas dataframe the file: car_radios.csv

In [ ]:
df = pd.read_csv('course_marks.csv')
df

FileNotFoundError: ignored

**FUNCTIONS**

Exercise 21 - Consider the dataset course_marks.csv. The three tests have the weights 25%, 40% and 35%, respectively.

Exercise 21a) Write a function that adds a column, named Final, to the dataframe with the final marks for each student.
ou seja, 15* 0.25+18* 0.4+12*0.35

In [ ]:
def calc_score(t1, t2, t3):
  score = t1*0.25 + t2*0.4 + t3*0.35
  return score

In [ ]:
calc_score(15, 18, 12)

15.149999999999999

In [ ]:
df = df['Score'] = [calc_score(x[0], x[1], x[2]) for x in zip(df['Test 1'], df['Test 2'], df['Test 3'])]

KeyError: ignored

Exercise 21b) Add the same column, using pandas only.

In [ ]:
df['Score2']:['Test 1'].mul(0.25)+df['Test 2'].mul(0.4)+df['Test'].mul(0.35)

KeyError: ignored

21c) Add the same column, using numpy only.