# KNN: K-Nearest Neighbors

(graph on tablet)

1. Define the number K of nearest neighbors.

2. Identify the K-nearest neighbors.

3. For the new point, the prediction will be the most frequent classe of the K-nearest neighbors.

- to identify the nearest neighbors we need to calculate the distance between the new example and all data points of the dataset.
- The most usual distance measure as the Euclidean distance.

Euclidean distance - distance between two points.
P1(1,2) and P2(3,4)

d(P1,P2) = `root[(3-1)^2+(4-2)^2]`

**KNN - Classification** 




In [13]:
df = pd.read_excel('/content/knn01_clas.xlsx')
df

X1  X2  Y
0   1   4  B
1   6   2  B
2   5   3  A
3   3   1  A
4   2   9  B
5   1   2  A

What is the predictors to the outcome variable for the point (X1,X2)=(3,5) by using KNN with K=3?

O ponto (3,5) não está no gráfico ainda, é um novo ponto e nós queremos ver a que classe ele pertence.

In [15]:
(df['X1'].values-3)**2

array([4, 9, 4, 0, 1, 4])

Instead of using X1 and 3 we use X2 and 5.

In [16]:
(df['X2'].values-5)**2

array([ 1,  9,  4, 16, 16,  9])

Now we need the squared root (remember the euclidean distance formula).

In [17]:
np.sqrt((df['X1'].values-3)**2 + (df['X2'].values-5)**2)

array([2.23606798, 4.24264069, 2.82842712, 4.        , 4.12310563,
       3.60555128])

In [19]:
df['dist'] = np.sqrt((df['X1'].values-3)**2 + (df['X2'].values-5)**2)
df

X1  X2  Y      dist
0   1   4  B  2.236068
1   6   2  B  4.242641
2   5   3  A  2.828427
3   3   1  A  4.000000
4   2   9  B  4.123106
5   1   2  A  3.605551

Now we need to identify the 3 nearest neighbors. How to do this? Sort the dataframe (ordenar).

In [20]:
df.sort_values('dist')

X1  X2  Y      dist
0   1   4  B  2.236068
2   5   3  A  2.828427
5   1   2  A  3.605551
3   3   1  A  4.000000
4   2   9  B  4.123106
1   6   2  B  4.242641

Agora temos o TOP3, e A é o mais frequente. Se tivessemos dois A e dois B, escolhiamos aleatoriamente dado os mais próximos.

Ver segundo gráfico tablet.

## KNN - REGRESSION

In [22]:
df = pd.read_excel('/content/knn01_reg.xlsx')
df

X1  X2   Y
0   1   4   8
1   6   2   5
2   5   3   7
3   3   1  10
4   2   9   3
5   1   2   6

What is the prediction for point (X2,X2)=(3,5), for K=3?


In [23]:
df['dist'] = np.sqrt((df['X1'].values-3)**2 + (df['X2'].values-5)**2)
df

X1  X2   Y      dist
0   1   4   8  2.236068
1   6   2   5  4.242641
2   5   3   7  2.828427
3   3   1  10  4.000000
4   2   9   3  4.123106
5   1   2   6  3.605551

The prediction for (X1,X2) = (3,5) will be `(8+5+7)/3=7`

How to implement this in Python?


In [24]:
from sklearn.neighbors import KNeighborsRegressor

In [25]:
X = df.drop(['Y', 'dist'], axis=1)
y = df['Y']

X => dataframe with all predictors

y => dataframe with only the outcome variable

In [28]:
X_new = pd.DataFrame({
    'X1':[3],
    'X2':[5]
})

In [29]:
X_new

X1  X2
0   3   5

Let's create the model.

In [30]:
knn_model = KNeighborsRegressor(n_neighbors=3)

Let's fit the model.

In [31]:
knn_model.fit(X,y)

knn_model.predict(X_new)

array([7.])

Chegamos ao mesmo valor que tinhamos previsto, só que agora foi o python que fez.

## KNN - EXAMPLE CLASSIFICATION

In [33]:
df = pd.read_excel('/content/knn01_clas.xlsx')
df

X1  X2  Y
0   1   4  B
1   6   2  B
2   5   3  A
3   3   1  A
4   2   9  B
5   1   2  A

In [35]:
from sklearn.neighbors import KNeighborsClassifier

In [37]:
X = df.drop(['Y'], axis=1)
y = df['Y']


In [38]:
knn_model = KNeighborsClassifier(n_neighbors=3)

In [39]:
knn_model.fit(X,y)

knn_model.predict(X_new)

array(['A'], dtype=object)

We will check if a set of bank notes are true.

We will see that the accuracy will be very high.

# KNN - BANK NOTES PROBLEM

Site: https://archive.ics.uci.edu/ml/datasets/banknote+authentication 

In [42]:
df = pd.read_csv('/content/data_banknote_authentication.txt')
df

3.6216    8.6661  -2.8073  -0.44699  0
0     4.54590   8.16740  -2.4586  -1.46210  0
1     3.86600  -2.63830   1.9242   0.10645  0
2     3.45660   9.52280  -4.0112  -3.59440  0
3     0.32924  -4.45520   4.5718  -0.98880  0
4     4.36840   9.67180  -3.9606  -3.16250  0
...       ...       ...      ...       ... ..
1366  0.40614   1.34920  -1.4501  -0.55949  1
1367 -1.38870  -4.87730   6.4774   0.34179  1
1368 -3.75030 -13.45860  17.5932  -2.77710  1
1369 -3.56370  -8.38270  12.3930  -1.28230  1
1370 -2.54190  -0.65804   2.6842   1.19520  1

[1371 rows x 5 columns]

Temos um problema com os nomes das colunas. Para corrigir.

In [44]:
df.columns = ['X1', 'X2', 'X3', 'X4', 'Y']
df

X1        X2       X3       X4  Y
0     4.54590   8.16740  -2.4586 -1.46210  0
1     3.86600  -2.63830   1.9242  0.10645  0
2     3.45660   9.52280  -4.0112 -3.59440  0
3     0.32924  -4.45520   4.5718 -0.98880  0
4     4.36840   9.67180  -3.9606 -3.16250  0
...       ...       ...      ...      ... ..
1366  0.40614   1.34920  -1.4501 -0.55949  1
1367 -1.38870  -4.87730   6.4774  0.34179  1
1368 -3.75030 -13.45860  17.5932 -2.77710  1
1369 -3.56370  -8.38270  12.3930 -1.28230  1
1370 -2.54190  -0.65804   2.6842  1.19520  1

[1371 rows x 5 columns]

This is a classification problem.

Preprocessing steps we need to take for this problem:


1. Define the X.

In [46]:
X = df.drop('Y', axis=1)
y = df['Y']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=45)

In [49]:
scaler = Pipeline([
    ('scale', StandardScaler())])

In [51]:
preprocessor = ColumnTransformer([
    ('scale_tr', scaler, X.columns.to_list())],
    remainder='passthrough')

#or
#preprocessor = ColumnTransformer([
#   ('scale_tr', scaler, ['X1', 'X2', 'X3', 'X4'])],
#   remainder='passthrough')

In [56]:
pipe = Pipeline([
    ('pre', preprocessor),
    ('knn', KNeighborsClassifier(n_neighbors=3))])

In [57]:
pipe.fit(X_train, y_train)

Pipeline(steps=[('pre',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('scale_tr',
                                                  Pipeline(steps=[('scale',
                                                                   StandardScaler())]),
                                                  ['X1', 'X2', 'X3', 'X4'])])),
                ('knn', KNeighborsClassifier(n_neighbors=3))])

In [58]:
y_pred = pipe.predict(X_train)

# CONFUSION MATRIX

We have predictons. Let's suppose that predictions will be 0 and 1 in this case, but the true values will also be 0 and 1 (False or True). We are predicting.

If our dataset has 50 false notes and 50 true notes => see tablet.

In [59]:
from sklearn.metrics import accuracy_score

In [60]:
y_pred = pipe.predict(X_train)
accuracy_score(y_train, y_pred)

0.9981751824817519

Accuracy is very good, the model is very good since accuracy is almost 100%.

Vamos fazer as predictions para o test set.

In [61]:
y_pred = pipe.predict(X_test)
accuracy_score(y_test, y_pred)

1.0

No error in the test set.

Next lecture - Vamos ver um caso em que a accuracy é mesmo muito boa, mas isso não é muito bom para nós.

Site: https://archive.ics.uci.edu/ml/datasets/bank+marketing 

Os valores positivos não vão estar bem predicted.